build:
	go build main.go && ./main



	    » {"places":{"_id":"3"}}
       » {"name":"Cotto Ital'janskaja Kofejnja","address":"gorod Moskva, Abramtsevskaja ulitsa, dom 9, korpus 1","phone":"(499) 200-00-22","location":{"lon":"37.57230613167112","lat":"55.90408636984904"}}
       « {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"},"status":400}


			 » {"index":{"_id":"3"}}
       » {"name":"Cotto Ital'janskaja Kofejnja","address":"gorod Moskva, Abramtsevskaja ulitsa, dom 9, korpus 1","phone":"(499) 200-00-22","location":{"lon":"37.57230613167112","lat":"55.90408636984904"}}
       « {"took":46,"errors":false,"items":[{"index":{"_index":"places","_id":"3","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1,"status":201}}]}