build:
	go build -o myFind ./cmd/app/find/main.go
	go build -o myWc ./cmd/app/wc/main.go
	go build -o myXargs ./cmd/app/xargs/main.go
	go build -o myRotate ./cmd/app/rotate/main.go

clean:
	rm -rf myFind myWc myXargs myRotate